// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq9Hbrm8-J0CZ-s2YPXKarajjRfy_hjY0',
    appId: '1:980400043732:web:588daa4edcf746390b2d41',
    messagingSenderId: '980400043732',
    projectId: 'first-project-a76cd',
    authDomain: 'first-project-a76cd.firebaseapp.com',
    storageBucket: 'first-project-a76cd.firebasestorage.app',
    measurementId: 'G-9VH27K3C34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxa3nHZUCzODnu6e9mBrcJBCCZEHZBGK0',
    appId: '1:980400043732:android:fe68adee33cc1cd70b2d41',
    messagingSenderId: '980400043732',
    projectId: 'first-project-a76cd',
    storageBucket: 'first-project-a76cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4xa76g8oUOp4sc4A1rrh9Akm2mJbNyiw',
    appId: '1:980400043732:ios:f3e0efc58492eac80b2d41',
    messagingSenderId: '980400043732',
    projectId: 'first-project-a76cd',
    storageBucket: 'first-project-a76cd.firebasestorage.app',
    iosBundleId: 'com.example.adminTelegramBot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4xa76g8oUOp4sc4A1rrh9Akm2mJbNyiw',
    appId: '1:980400043732:ios:f3e0efc58492eac80b2d41',
    messagingSenderId: '980400043732',
    projectId: 'first-project-a76cd',
    storageBucket: 'first-project-a76cd.firebasestorage.app',
    iosBundleId: 'com.example.adminTelegramBot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq9Hbrm8-J0CZ-s2YPXKarajjRfy_hjY0',
    appId: '1:980400043732:web:12c0e4676d38f3b80b2d41',
    messagingSenderId: '980400043732',
    projectId: 'first-project-a76cd',
    authDomain: 'first-project-a76cd.firebaseapp.com',
    storageBucket: 'first-project-a76cd.firebasestorage.app',
    measurementId: 'G-V1JMHF90MW',
  );

}